### ISSUE TITLE
Erratic SRTM elevations

### ISSUE THREAD

**Issue by hrpunio** [tkrajina/srtm.py#15]
I compare gpxelevations with gpsprune (http://activityworkshop.net/software/gpsprune/) and googleAPI (for a certain GPX track). Using RMSE (root mean square error) I have got 1,2 meter average difference for gpsprune versus googleAPI while almost 4 meters for gpselevations versus googleAPI/gpsprune (4 times more or 400%).
Looking at plotted values (http://fabianserwis.homelinux.com/p/) I have discovered a few areas of suspiciously erratic elevations
Any explanation?

**Comment by tkrajina** [comment]
Nope, I have no idea what could be wrong.

If somebody else have an explanation and is willing to fix it (in case there is a bug), I'm willing to merge it.
