### ISSUE TITLE
Negative elevations (below zero) are not added

### ISSUE THREAD

**Issue by fbonzon** [tkrajina/srtm.py#16]
It seems a bug prevents negative elevation values (below 0 m) to be added.

E.g. with sample GPX file [below_zero.gpx](https://github.com/tkrajina/srtm.py/files/333927/below_zero.gpx.zip) close to Dead Sea, at altitude around −400 m, no elevations are added with the command-line utility:
```
gpxelevations below_zero.gpx
```

**Comment by tkrajina** [comment]
Yes, looks like you're right. 

This should fix your problem: fc67fa260c55649ef0e8c90dcc41495cbe11dd1c

**Comment by fbonzon** [comment]
Many thanks for the fast fix. I confirm this solves the issue.
