### ISSUE TITLE
import Image

### ISSUE THREAD

**Issue by ElmWer** [tkrajina/srtm.py#20]
using srtm_obj.get_image i got the following error

-  ImportError: No module named 'Image'

Could you please change the imports in srtm/data.py line 158 and 159 to

from PIL import Image as mod_image
from PIL import ImageDraw as mod_imagedraw

**Comment by tkrajina** [comment]
Commited in https://github.com/tkrajina/srtm.py/commit/85135696eca3c97de74960a7678559e7106d5c7e

Thanks!
