### ISSUE TITLE
Python2 or Python3

### ISSUE THREAD

**Issue by andischan** [tkrajina/srtm.py#24]
I get this error:
```
  File "/usr/lib/python3.6/site-packages/srtm/data.py", line 29, in <module>
    import cStringIO as mod_cstringio
```
Is srtm.py a python2 package?

**Comment by MaxyMoos** [comment]
No problem using srtm.py with Python 3.5.2 over here.
Python 3.6-specific error ?

**Comment by andischan** [comment]
Yes, I have Python 3.6.

**Comment by MaxyMoos** [comment]
Can you try using another version of Python on your system - such as 3.5.2 - to see whether this is an error specific to Python 3.6 or not ?

**Comment by andischan** [comment]
Honestly I'm not using a dev system and don't want to downgrade.
I'm running the demo.py script with Python 3.6 and it works perfect.
