### ISSUE TITLE
pip install requirements are not specified

### ISSUE THREAD

**Issue by sladkovm** [tkrajina/srtm.py#41]
Upon `import srtm` the following error pops up: `ModuleNotFoundError: No module named 'requests'`

Solution: add requests to the requirements.txt

**Comment by iblasi** [comment]
@sladkovm, as you can see on the code ``master/srtm/data.py`` line 28, it requires ``requests`` package that can be intalled easily with pip (or conda for Windows environment).
http://docs.python-requests.org/en/master/

**Comment by tkrajina** [comment]
Should be fixed with fb80e6ad114c4857ae0112edc378b55cb53261d4, try it now.
