### ISSUE TITLE
[WinError 53]:The network path on WINDOWS-10 machine 

### ISSUE THREAD

**Issue by vignesh1987** [tkrajina/srtm.py#46]
Hi,
I am trying to test the ridge_map package. But I get a windows error when I try the first steps as described on the Github page
[WinError 53] The network path was not found: '\\\\.cache\\srtm'
![ridge map error](https://user-images.githubusercontent.com/33900146/70949546-57c89800-205e-11ea-8839-e4e52615f05f.png)

I ran it through the Ridge map creator. He suggested some changes to the srtm.py code, which is creating this issue on WINDOWS 10 machines. But it did not solve my problem. 
Can you help?

best
Vignesh

**Comment by tkrajina** [comment]
I pushed a new commit on `master` now. Can you try if it fixes your problem

**Comment by vignesh1987** [comment]
Hi,
I uninstalled the older version (srtm.py) and reinstalled the master version from Github. I get the following (same) error
![image](https://user-images.githubusercontent.com/33900146/71033574-d7ff0400-2117-11ea-9e84-04f1769dd43c.png)

**Comment by tkrajina** [comment]
OK, two things, first can you start python in interactive mode and try:
```
$ python
Python 3.7.3 (default, Nov 15 2019, 04:04:52) 
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ.get("HOME")
'/Users/usr'
>>> os.environ.get("HOMEPATH")
>>> import pathlib
>>> pathlib.Path.home()
PosixPath('/Users/usr')
```
...and paste the results. To me, it seems like Python detects that your home directory `\\` and it's not writeable.

Second, I pushed another commit, it will fail again, but I'm interested in the error message it fails with.

And third. I added a new parameter to use a custom local cache directory (that's the directory SRTM files are stored). See https://github.com/tkrajina/srtm.py/blob/master/example.py -- can you try if this works for you?

**Comment by vignesh1987** [comment]
Hi,
The python command gives me the following output. you were correct about the home directory (\\)
![image](https://user-images.githubusercontent.com/33900146/71074495-a96a4300-2182-11ea-9659-856f6d839476.png)

The second  option fails as well with a similar message
![image](https://user-images.githubusercontent.com/33900146/71074949-868c5e80-2183-11ea-9b94-f374108498c0.png)

The third local cache directory works
![image](https://user-images.githubusercontent.com/33900146/71074996-9c9a1f00-2183-11ea-8085-103008a69ee7.png)

**Comment by tkrajina** [comment]
Ah, OK, I see.

I pushed another change (https://github.com/tkrajina/srtm.py/commit/075126875bedbee0f23676f4a8159c6240398a95) which should fix the library even without the custom directory.
