### ISSUE TITLE
Cannot retrieve Eurasia/N55W004.hgt.zip

### ISSUE THREAD

**Issue by christiancampbell33** [tkrajina/srtm.py#50]
Hi there,

I've been using this fantastic package without issues for months (thank you).
However, today I tried gathering some obstacle points for EGPH airport in the UK and ran into this issue (which isn't happening in my other test areas):
"Exception: Cannot retrieve http://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Eurasia/N55W004.hgt.zip"

Any ideas what could be causing this issue? 

(Branch is FlorianWilhelm-py3_comp if that helps)

Thanks for your help.

**Comment by tkrajina** [comment]
I think it's something on NASA's servers. Because some other hgt files fail to load for me, too. 

And also, from their website (https://www2.jpl.nasa.gov/srtm/):

> The data may be obtained through this URL: http://dds.cr.usgs.gov/srtm/ and go to the directory where both version 1 and version 2 directories may be found. Please read the appropriate documentation, also found in the directories.

Well, this link (`http://dds.cr.usgs.gov/srtm/`) at the moment fails with a `403` error.

**Comment by christiancampbell33** [comment]
Thanks for your response and confirmation of what I was thinking. 

The website is back up without issue now and I was able to collect the elevation points for the region I mentioned without a problem any more.
