### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by mattiabl** [tkrajina/srtm.py#9]
I am trying to install the package after downloading the .zip file.
System: Macbook pro - OSx yosemite 10.10.1.

Installing from the terminal I get the following error:

Mattias-MBP:srtm.py-master mattiazanon$ python setup.py install
/Applications/anaconda/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
running install
running build
running build_py
running build_scripts
running install_lib
byte-compiling /Applications/anaconda/lib/python3.4/site-packages/srtm/retriever.py to retriever.cpython-34.pyc
  File "/Applications/anaconda/lib/python3.4/site-packages/srtm/retriever.py", line 65
    print get_geo_elevation_data()
                               ^
SyntaxError: invalid syntax

running install_scripts
changing mode of /Applications/anaconda/bin/gpxelevations to 755
running install_egg_info
Removing /Applications/anaconda/lib/python3.4/site-packages/SRTM.py-0.2.4-py3.4.egg-info
Writing /Applications/anaconda/lib/python3.4/site-packages/SRTM.py-0.2.4-py3.4.egg-info

**Comment by tkrajina** [comment]
You are using python3. This library works with python2, but it shouldn't be hard to refactor it for py3. I changed a few things earlier today but it is not yet finished... I'll do it when I find some time in the next few weeks (of course, help is welcome :)

**Comment by tkrajina** [comment]
python 3 should work now (see https://github.com/tkrajina/srtm.py/pull/18)
